### PR TITLE
Inisiasi Project 1

### PR DESCRIPTION
**Pull request by aldoKelvianto**
TODO:
- [x] Menentukan _code name_ proyek 1
- [x] Mengumpulkan relawan
- [ ] Product Owner - Membuat dokumen untuk MVP

### CODE REVIEW

**Comment by ibrdrahim** [comment]
- Ibrahim :  Ios Mobile Developer (NATIVE)

**Comment by zakuby** [comment]
- Yaqub : Android / Ios Mobile Developer (NATIVE)

**Comment by fuadsuyudi** [comment]
- Fuad Suyudi : Back End Developer

**Comment by lorenzadam** [comment]
Lorenz Adam Damara : Copy Writer

**Comment by Kyald1412** [comment]
- Dhiky Aldwiansyah : Android / iOS Native Developer

**Comment by ynwd** [comment]
ynwd: fullstack-dev

**Comment by ayatmaulana** [comment]
- ayatmaulana : Devops + AWS Donatur

**Comment by asrini07** [comment]
Asrini : QA

**Comment by yeppymp** [comment]
Yeppy : UI Designer / Frontend Developer

**Comment by onadmeister** [comment]
Rienaldi : Backend Dev

**Comment by affandi2204** [comment]
Affandi : QA

**Comment by ans-4175** [comment]
Ans: Project Maintainer

**Comment by aldoKelvianto** [comment]
Aldo: Product Owner.
Aldo: Android Developer - Mostly Code Reviewer.

**Comment by robihidayat** [comment]
Robi: Backend.

**Pull request merged**
